### ISSUE TITLE
Getting an error when I try to add a stock to the list

### ISSUE THREAD

**Issue by seansodhaibm** [IBM/watson-stock-advisor#86] opened 2018-11-15 15:51 UTC
<img width="1606" alt="screen shot 2018-11-09 at 4 02 50 pm" src="https://user-images.githubusercontent.com/41637300/48564420-5c9fa300-e8c4-11e8-9f0b-ec5acccfa702.png">

This is what appears on the console: 

<img width="1641" alt="screen shot 2018-11-09 at 4 05 20 pm" src="https://user-images.githubusercontent.com/41637300/48564457-717c3680-e8c4-11e8-8df6-0e50824d4a9b.png">

Kindly advise.

**Comment by scottdangelo** [comment] 2018-11-15 16:27
Are you running this locally? You will need to change the `ALPHAVANTAGE_API_KEY` in the `.env` file:
```
# AlphaVantage
ALPHAVANTAGE_API_KEY="demo"
```
You get this when you do the [Prerequisites](https://github.com/IBM/watson-stock-advisor#prerequisites).

**Comment by seansodhaibm** [comment] 2018-11-15 16:30
This is my current .env file: 

<img width="703" alt="screen shot 2018-11-09 at 4 20 07 pm" src="https://user-images.githubusercontent.com/41637300/48566850-c8d0d580-e8c9-11e8-8432-27584a4b3808.png">

**Comment by scottdangelo** [comment] 2018-11-15 17:46
See comments above.
Your current value for `ALPHAVANTAGE_API_KEY` is `"demo"`.
That is why the app does not work.
You need to get an Alphavantage API key by following the instructions in the [Prerequisites](https://github.com/IBM/watson-stock-advisor#prerequisites) and put it in the `.env` file, just as you have done for the others in that file.

**Comment by scottdangelo** [comment] 2018-11-15 18:05
User is still seeing the issue after adding API key

**Comment by rhagarty** [comment] 2018-11-16 17:40
I could not reproduce Sean's error, even when using the .env file supplied here. 

Looking at Sean's system, I did notice some permission issues on some directories (owned by root). This caused problems when running "npm install" as it also does some global installs into these directories. After changing the ownership of these directories, install completed without error, but he is still seeing the run-time UI errors. Maybe there are other permission issues?

**Comment by stevemar** [comment] 2019-02-19 20:44
Closing as we were unable to reproduce.

**Closed as completed by stevemar** 2019-02-19 20:44 UTC

**Comment by Avejack** [comment] 2019-03-05 13:35
I have the same issue. The Error says "TypeError: Cannot read property 'document' of undefined" but i only get this, when I try to add the Apple Inc Stock.

When I add any other Stock it isn't throwing an Alarm as Error but it can't get the Prices from Alpha Vantage because the Query is Invalid. I looked into it and the Query is invalid because the "Symbol" gets set as "No Ticker Found".

This is because your "config.companies" array always has an "\r" character at the end. But the inputted "name" variable hasn't.

Also, News aren't getting displayed.

The Easy solution: All your files are saved as "CRLF" instead of "LF". If you go into the ".txt" files and change CRLF to LF endings everything works fine except for the Apple Inc part.
