### ISSUE TITLE
getting a no ticker found error when i add a company

### ISSUE THREAD

**Issue by shyrynaz** [IBM/watson-stock-advisor#90] opened 2019-02-19 02:38 UTC
When adding a company, in the drop down the ticker is visible but on adding it returns no ticker found.
here is my console output 
![stock error](https://user-images.githubusercontent.com/31190596/52986234-219f9500-3408-11e9-811e-f736f47235a1.PNG)

**Comment by stevemar** [comment] 2019-02-19 20:58
@rhagarty can you take a look?

**Comment by rhagarty** [comment] 2019-02-20 16:55
@shyrynaz - wasn't able to reproduce this issue. Any other data points you can provide, such as how many stocks did you add before this?, etc...

![screen shot 2019-02-20 at 8 53 01 am](https://user-images.githubusercontent.com/12628378/53109164-2b4ef880-34ed-11e9-8f51-1e2e78169a5b.png)

**Comment by creitz** [comment] 2019-02-20 17:05
I don't know what would have caused it but it looks like there is a newline character at the end of 1St Constitution Bcp in the error screenshot. My guess is the result "No Ticker Found" is occurring because it is not matching the string exactly when searching through companies because of the newline character

**Comment by stevemar** [comment] 2019-02-20 17:19
@creitz that was my guess also, the extra newline looks like it's causing a mis-match. Maybe we can trim whitespace on the input from that textbox before looking for a match?

**Comment by creitz** [comment] 2019-02-20 17:48
Possibly, but that might be a bandaid approach. Last time I ran it the stock was selected from a dropdown, rather than freeform input, is that still the case? If so we will want to find where the extra newline char is coming from as it might cause issues elsewhere.

**Comment by rhagarty** [comment] 2019-02-20 20:02
It appears that the drop-down is the only way to add a stock. And the ticker is displayed along with the company name in the drop-down. Maybe he modified the data files that contain all of the companies/tickers?

**Comment by stevemar** [comment] 2019-02-20 20:40
Closing this as it cannot be reproduced.

@shyrynaz please re-open if you're still running into trouble. See above comments.

**Closed as completed by stevemar** 2019-02-20 20:40 UTC

**Comment by shyrynaz** [comment] 2019-02-24 12:51
am still getting the same error. when i add a company i get the sentiment and the articles but not the stock data.
